export enum QuestionType {
  MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
  MULTIPLE_RESPONSE = "MULTIPLE_RESPONSE",
  TRUE_FALSE = "TRUE_FALSE",
  MATCHING = "MATCHING",
  ORDERING = "ORDERING",
  HOTSPOT = "HOTSPOT",
}
